#!/home/yangjiekun/venv-py3/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import os

dirpath = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, dirpath)

from netron_src import main


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
